#!/usr/bin/env python3
"""Generate docs/api.md from live introspection of the ams02wb package.

Enumerates all public functions and classes across ams02wb subpackages,
extracts signatures and docstring first lines, and flags provenance field access.
"""

from __future__ import annotations

import importlib
import inspect
import pathlib
import pkgutil
import types
from collections.abc import Callable
from collections.abc import Generator
from typing import Any

SUBPACKAGES = [
    "ams02wb.crawler",
    "ams02wb.parsers",
    "ams02wb.schema",
    "ams02wb.harmoniser",
    "ams02wb.likelihood",
    "ams02wb.alignment",
    "ams02wb.exports",
    "ams02wb.cli",
]

PROVENANCE_MARKERS = ("provenance_json", "publication_url", "provenance")


def _provenance_note(obj: Callable[..., Any] | type[Any]) -> str:
    """Scan source for provenance-related field access."""
    try:
        src = inspect.getsource(obj)
    except (OSError, TypeError):
        return "none"

    reads = any(f".{m}" in src or f"['{m}']" in src or f'["{m}"]' in src for m in PROVENANCE_MARKERS)
    writes = any(f"{m} =" in src or f"{m}=" in src for m in PROVENANCE_MARKERS)

    if reads and writes:
        return "reads_provenance / writes_provenance"
    if writes:
        return "writes_provenance"
    if reads:
        return "reads_provenance"

    # Check if provenance fields appear in function signature (passes through)
    try:
        sig = inspect.signature(obj)
        if any(m in str(sig) for m in PROVENANCE_MARKERS):
            return "passes_through"
    except (ValueError, TypeError):
        pass

    return "none"


def _first_docstring_line(obj: Callable[..., Any] | type[Any]) -> str:
    doc = inspect.getdoc(obj)
    if not doc:
        return ""
    return doc.strip().split("\n")[0]


def _get_signature(obj: Callable[..., Any] | type[Any]) -> str:
    try:
        return str(inspect.signature(obj))
    except (ValueError, TypeError):
        return "(…)"


def _collect_members(module: types.ModuleType) -> Generator[tuple[str, Any, str], None, None]:
    """Yield (name, obj, kind) for public functions and classes in module."""
    for name, obj in sorted(inspect.getmembers(module)):
        if name.startswith("_"):
            continue
        if not (inspect.isfunction(obj) or inspect.isclass(obj)):
            continue
        # Only include objects defined in this module
        if getattr(obj, "__module__", None) != module.__name__:
            continue
        kind = "class" if inspect.isclass(obj) else "function"
        yield name, obj, kind


def generate_api_reference() -> str:
    """Generate the full API reference markdown string."""
    lines: list[str] = []
    missing_docstrings: list[str] = []

    lines.append("# API Reference")
    lines.append("")
    lines.append("Auto-generated by `scripts/gen_api_ref.py` — do not edit manually.")
    lines.append("")

    for pkg_name in SUBPACKAGES:
        try:
            pkg = importlib.import_module(pkg_name)
        except ImportError:
            lines.append(f"## {pkg_name}")
            lines.append("")
            lines.append("*Could not import package.*")
            lines.append("")
            continue

        # Collect all submodules
        pkg_path = getattr(pkg, "__path__", None)
        submodules = []
        if pkg_path:
            for importer, modname, ispkg in pkgutil.walk_packages(pkg_path, prefix=pkg_name + "."):
                if ispkg:
                    continue
                try:
                    submodules.append(importlib.import_module(modname))
                except ImportError:
                    continue

        # If no submodules found, treat the package itself as the module
        if not submodules:
            submodules = [pkg]

        section_lines: list[str] = []

        for mod in sorted(submodules, key=lambda m: m.__name__):
            members = list(_collect_members(mod))
            if not members:
                continue

            section_lines.append(f"### {mod.__name__}")
            section_lines.append("")
            section_lines.append("| Function/Class | Signature | Description | Provenance Note |")
            section_lines.append("|---|---|---|---|")

            for name, obj, kind in members:
                sig = _get_signature(obj)
                desc = _first_docstring_line(obj)
                prov = _provenance_note(obj)

                if not desc:
                    missing_docstrings.append(f"{mod.__name__}.{name}")
                    desc = "*(no docstring)*"

                # Escape pipes in signatures
                sig = sig.replace("|", "\\|")
                desc = desc.replace("|", "\\|")

                label = f"`{name}` ({kind})" if kind == "class" else f"`{name}`"
                section_lines.append(f"| {label} | `{sig}` | {desc} | {prov} |")

                # For classes, also list public methods defined on the class itself
                if kind == "class":
                    for mname, mobj in sorted(inspect.getmembers(obj)):
                        if mname.startswith("_"):
                            continue
                        if not (inspect.isfunction(mobj) or inspect.ismethod(mobj)):
                            continue
                        # Skip inherited methods (Pydantic, dataclass, object builtins)
                        defining_class = None
                        for cls in inspect.getmro(obj):
                            if mname in cls.__dict__:
                                defining_class = cls
                                break
                        if defining_class is not obj:
                            continue
                        msig = _get_signature(mobj)
                        mdesc = _first_docstring_line(mobj)
                        mprov = _provenance_note(mobj)
                        if not mdesc:
                            missing_docstrings.append(f"{mod.__name__}.{name}.{mname}")
                            mdesc = "*(no docstring)*"
                        msig = msig.replace("|", "\\|")
                        mdesc = mdesc.replace("|", "\\|")
                        section_lines.append(f"| `{name}.{mname}` | `{msig}` | {mdesc} | {mprov} |")

            section_lines.append("")

        if section_lines:
            lines.append(f"## {pkg_name}")
            lines.append("")
            lines.extend(section_lines)
        else:
            lines.append(f"## {pkg_name}")
            lines.append("")
            lines.append("*No public functions or classes found.*")
            lines.append("")

    # Missing docstrings section
    lines.append("## Missing Docstrings")
    lines.append("")
    if missing_docstrings:
        lines.append("The following public functions/classes/methods are missing Google-style docstrings:")
        lines.append("")
        for item in sorted(missing_docstrings):
            lines.append(f"- `{item}`")
    else:
        lines.append("All public functions and classes have docstrings.")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    content = generate_api_reference()
    out = pathlib.Path("docs/api.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    print(f"Wrote {out} ({len(content)} chars, {len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
